In [1]:
import statistics
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [2]:
DATAp = Path("/home/oussama/Dirhamflow/data/raw/raw_data")

In [4]:
print(DATAp)

/home/oussama/Dirhamflow/data/raw/raw_data

In [5]:
accounts_PATH = DATAp / "accounts.csv"

In [6]:
accounts_PATH = DATAp / "accounts.csv"
customers_PATH = DATAp / "customers.csv"
transactions_PATH= DATAp /"transactions.csv"
cards_PATH= DATAp /"cards.csv"
payment_errors_PATH= DATAp /"payment_errors.csv"
credit_risk_bureau_PATH= DATAp /"credit_risk_bureau.csv"
support_tickets_PATH= DATAp /"support_tickets.csv"

In [7]:
acc = pd.read_csv(accounts_PATH)
custm= pd.read_csv(customers_PATH)
trans= pd.read_csv(transactions_PATH)
card= pd.read_csv(cards_PATH)
pay_err= pd.read_csv(payment_errors_PATH)
credit_risk= pd.read_csv(credit_risk_bureau_PATH)
sup_tik= pd.read_csv(support_tickets_PATH)

In [8]:
acc.head(5)

,account_id,customer_id,account_type,account_tier,currency,created_at,account_status
0,ACC_000001,CUST_006021,CHECKING,PREMIUM,MAD,2026-07-10 03:58:37,ACTIVE
1,ACC_000002,CUST_006509,MULTI_CURRENCY,STANDARD,MAD,2025-10-24 20:10:27,ACTIVE
2,ACC_000003,CUST_002371,MULTI_CURRENCY,STANDARD,MAD,2024-03-21 11:50:44,ACTIVE
3,ACC_000004,CUST_004788,SAVINGS,STANDARD,MAD,2024-06-28 20:34:08,DORMANT
4,ACC_000005,CUST_009082,CHECKING,STANDARD,MAD,2026-05-15 16:48:36,DORMANT

In [9]:
acc.shape

(14000, 7)

In [10]:
acc.tail(5)

,account_id,customer_id,account_type,account_tier,currency,created_at,account_status
13995,ACC_013996,CUST_004639,SAVINGS,PLUS,MAD,2025-09-23 19:12:49,ACTIVE
13996,ACC_013997,CUST_007423,CHECKING,STANDARD,MAD,2025-06-23 13:37:52,DORMANT
13997,ACC_013998,CUST_004937,CHECKING,STANDARD,MAD,2024-11-16 09:14:44,ACTIVE
13998,ACC_013999,CUST_008335,SAVINGS,PLUS,MAD,2026-06-17 00:35:42,FROZEN
13999,ACC_014000,CUST_000452,CHECKING,PREMIUM,MAD,2024-04-22 16:44:24,ACTIVE

In [11]:
acc.info()

<class 'pandas.DataFrame'>
RangeIndex: 14000 entries, 0 to 13999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   account_id      14000 non-null  str
 1   customer_id     14000 non-null  str
 2   account_type    14000 non-null  str
 3   account_tier    14000 non-null  str
 4   currency        14000 non-null  str
 5   created_at      14000 non-null  str
 6   account_status  14000 non-null  str
dtypes: str(7)
memory usage: 1.6 MB

In [12]:
Sacc

NameError: name 'Sacc' is not defined

In [13]:
acc.nunique()

account_id        14000
customer_id        9206
account_type          4
account_tier          4
currency              3
created_at        13980
account_status        4
dtype: int64

In [14]:
acc.isnull().sum()

account_id        0
customer_id       0
account_type      0
account_tier      0
currency          0
created_at        0
account_status    0
dtype: int64

In [15]:
(acc.isnull().sum()/(len(acc)))*100

account_id        0.0
customer_id       0.0
account_type      0.0
account_tier      0.0
currency          0.0
created_at        0.0
account_status    0.0
dtype: float64

In [16]:
acc['account_type'].value_counts()

account_type
CHECKING          10038
SAVINGS            2575
MULTI_CURRENCY      868
BUSINESS            519
Name: count, dtype: int64

In [17]:
acc['account_tier'].value_counts()

account_tier
STANDARD    9614
PLUS        2766
PREMIUM     1218
VIP          402
Name: count, dtype: int64

In [18]:
acc['currency'].value_counts()

currency
MAD    13329
EUR      399
USD      272
Name: count, dtype: int64

In [19]:
acc['account_status'].value_counts()

account_status
ACTIVE     11779
DORMANT     1151
FROZEN       672
CLOSED       398
Name: count, dtype: int64

In [20]:
custm.head(5)

,customer_id,signup_timestamp,birth_date,city,monthly_income,occupation,kyc_status,device_os,referral_code
0,CUST_000001,2026-01-30 13:14:27,20/09/1999,Rabat,4600.0,Software Engineer,VERIFIED,iOS,NaN
1,CUST_000002,2025-10-19 05:17:16,22/07/2008,Tangier,NaN,Freelancer,VERIFIED,Android,REF_2446_VIP
2,CUST_000003,2025-10-20 16:38:02,2007-12-27,Casablanca,NaN,Software Engineer,REJECTED,Android,NaN
3,CUST_000004,2024-09-01 08:03:08,1993-09-16,Fes,7200.0,Merchant,VERIFIED,Android,NaN
4,CUST_000005,2024-06-03 10:38:12,1998-11-28,Casablanca,7800.0,Teacher,VERIFIED,Android,NaN

In [21]:
custm.info(5)

<class 'pandas.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10100 non-null  str
 1   signup_timestamp  10100 non-null  str
 2   birth_date        10100 non-null  str
 3   city              10100 non-null  str
 4   monthly_income    8946 non-null   float64
 5   occupation        10100 non-null  str
 6   kyc_status        10100 non-null  str
 7   device_os         10100 non-null  str
 8   referral_code     3546 non-null   str
dtypes: float64(1), str(8)
memory usage: 1.4 MB

In [22]:
custm.info(5)

<class 'pandas.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       10100 non-null  str
 1   signup_timestamp  10100 non-null  str
 2   birth_date        10100 non-null  str
 3   city              10100 non-null  str
 4   monthly_income    8946 non-null   float64
 5   occupation        10100 non-null  str
 6   kyc_status        10100 non-null  str
 7   device_os         10100 non-null  str
 8   referral_code     3546 non-null   str
dtypes: float64(1), str(8)
memory usage: 1.4 MB

In [23]:
custm.shape

(10100, 9)

In [24]:
custm.nunique()

customer_id         10000
signup_timestamp     9999
birth_date           7995
city                   14
monthly_income        269
occupation             10
kyc_status              4
device_os               3
referral_code        3329
dtype: int64

In [25]:
custm.isnull().sum()

customer_id            0
signup_timestamp       0
birth_date             0
city                   0
monthly_income      1154
occupation             0
kyc_status             0
device_os              0
referral_code       6554
dtype: int64

In [26]:
custm.tail(10)

,customer_id,signup_timestamp,birth_date,city,monthly_income,occupation,kyc_status,device_os,referral_code
10090,CUST_007439,2025-06-23 02:12:01,1991-10-09,Agadir,9700.0,Accountant,VERIFIED,Android,NaN
10091,CUST_007943,2024-07-13 13:13:32,1999-09-30,Marrakech,15800.0,Accountant,VERIFIED,Android,NaN
10092,CUST_009239,2025-06-14 22:34:07,2004-04-02,Casablanca,5300.0,Student,VERIFIED,iOS,REF_4674_MA
10093,CUST_001057,2024-03-13 00:32:36,27/12/2000,Tangier,NaN,Sales Representative,VERIFIED,Web,NaN
10094,CUST_003155,2025-07-18 08:15:09,1982-11-27,Casablanca,9300.0,Accountant,VERIFIED,Android,NaN
10095,CUST_003788,2024-04-09 08:42:15,1977-06-16,Casablanca,7800.0,Merchant,PENDING,Android,REF_7955_APP
10096,CUST_009190,2026-06-14 04:51:13,1996-10-07,casa,5200.0,Doctor,PENDING,Android,REF_5084_APP
10097,CUST_007826,2026-02-06 06:33:07,1991-02-18,kech,2500.0,Software Engineer,VERIFIED,Android,NaN
10098,CUST_007540,2025-02-10 08:18:20,2004-06-30,casa,27100.0,Merchant,EXPIRED,Android,NaN
10099,CUST_007232,2024-05-12 03:43:55,1993-09-28,Rabat,7900.0,Merchant,VERIFIED,Android,NaN