In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [7]:
DATAp = Path("/home/oussama/Dirhamflow/data/raw/raw_data")

In [8]:
print(p)

/home/oussama/Dirhamflow/data/raw/raw_data

In [10]:
accounts_PATH = DATAp / "accounts.csv"

In [12]:
accounts_PATH = DATAp / "accounts.csv"
customers_PATH = DATAp / "customers.csv"
transactions_PATH= DATAp /"transactions.csv"
cards_PATH= DATAp /"cards.csv"
payment_errors_PATH= DATAp /"payment_errors.csv"
credit_risk_bureau_PATH= DATAp /"credit_risk_bureau.csv"
support_tickets_PATH= DATAp /"support_tickets.csv"

In [38]:
acc = pd.read_csv(accounts_PATH)
custm= pd.read_csv(customers_PATH)
trans= pd.read_csv(transactions_PATH)
card= pd.read_csv(cards_PATH)
pay_err= pd.read_csv(payment_errors_PATH)
credit_risk= pd.read_csv(credit_risk_bureau_PATH)
sup_tik= pd.read_csv(support_tickets_PATH)

In [39]:
acc.head(5)

,account_id,customer_id,account_type,account_tier,currency,created_at,account_status
0,ACC_000001,CUST_006021,CHECKING,PREMIUM,MAD,2026-07-10 03:58:37,ACTIVE
1,ACC_000002,CUST_006509,MULTI_CURRENCY,STANDARD,MAD,2025-10-24 20:10:27,ACTIVE
2,ACC_000003,CUST_002371,MULTI_CURRENCY,STANDARD,MAD,2024-03-21 11:50:44,ACTIVE
3,ACC_000004,CUST_004788,SAVINGS,STANDARD,MAD,2024-06-28 20:34:08,DORMANT
4,ACC_000005,CUST_009082,CHECKING,STANDARD,MAD,2026-05-15 16:48:36,DORMANT

In [37]:
acc.shape

(14000, 7)

In [42]:
acc.tail(5)

,account_id,customer_id,account_type,account_tier,currency,created_at,account_status
13995,ACC_013996,CUST_004639,SAVINGS,PLUS,MAD,2025-09-23 19:12:49,ACTIVE
13996,ACC_013997,CUST_007423,CHECKING,STANDARD,MAD,2025-06-23 13:37:52,DORMANT
13997,ACC_013998,CUST_004937,CHECKING,STANDARD,MAD,2024-11-16 09:14:44,ACTIVE
13998,ACC_013999,CUST_008335,SAVINGS,PLUS,MAD,2026-06-17 00:35:42,FROZEN
13999,ACC_014000,CUST_000452,CHECKING,PREMIUM,MAD,2024-04-22 16:44:24,ACTIVE

In [44]:
acc.info()

<class 'pandas.DataFrame'>
RangeIndex: 14000 entries, 0 to 13999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   account_id      14000 non-null  str
 1   customer_id     14000 non-null  str
 2   account_type    14000 non-null  str
 3   account_tier    14000 non-null  str
 4   currency        14000 non-null  str
 5   created_at      14000 non-null  str
 6   account_status  14000 non-null  str
dtypes: str(7)
memory usage: 1.6 MB

In [45]:
acc.nunique()

account_id        14000
customer_id        9206
account_type          4
account_tier          4
currency              3
created_at        13980
account_status        4
dtype: int64

In [46]:
acc.isnull().sum()

account_id        0
customer_id       0
account_type      0
account_tier      0
currency          0
created_at        0
account_status    0
dtype: int64

In [49]:
(acc.isnull().sum()/(len(acc)))*100

account_id        0.0
customer_id       0.0
account_type      0.0
account_tier      0.0
currency          0.0
created_at        0.0
account_status    0.0
dtype: float64

In [50]:
acc['account_type'].value_counts()

account_type
CHECKING          10038
SAVINGS            2575
MULTI_CURRENCY      868
BUSINESS            519
Name: count, dtype: int64

In [52]:
acc['account_tier'].value_counts()

account_tier
STANDARD    9614
PLUS        2766
PREMIUM     1218
VIP          402
Name: count, dtype: int64

In [53]:
acc['currency'].value_counts()

currency
MAD    13329
EUR      399
USD      272
Name: count, dtype: int64

In [54]:
acc['account_status'].value_counts()

account_status
ACTIVE     11779
DORMANT     1151
FROZEN       672
CLOSED       398
Name: count, dtype: int64

In [ ]:
S